# Dockerfile.base
ARG PYTHON_VERSION=3.11.3
FROM python:${PYTHON_VERSION}-alpine3.18 AS poetry_base

WORKDIR /app

# Устанавливаем Poetry и зависимости
COPY pyproject.toml poetry.lock ./

RUN pip install --no-cache-dir poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-root --no-interaction --no-ansi

ENV PYTHONUNBUFFERED=1
