# bot/dockerfile
FROM poetry_base

WORKDIR /app/bot
COPY ./bot ./

# Для разработки
CMD ["poetry", "run", "python", "main.py", "--reload"]

# Для продакшена
# CMD ["poetry", "run", "python", "main.py"]